import { ArrowRight, Check, PenLine, Search, Sparkles, WandSparkles } from "lucide-react";
import { startKakaoLogin } from "@/const";

const features = [
  { icon: PenLine, title: "브랜드 톤을 기억하는 글쓰기", body: "기존 글을 분석해 우리 매장만의 말투와 문장 습관을 초안에 반영합니다." },
  { icon: Search, title: "검색 의도를 읽는 SEO 점검", body: "키워드 배치와 가독성을 점검하고, 수정해야 할 이유까지 쉽게 안내합니다." },
  { icon: WandSparkles, title: "사진에서 썸네일까지", body: "원본 사진과 스타일을 고르면 네이버 블로그에 어울리는 이미지를 준비합니다." },
];

export default function Landing() {
  return <div className="min-h-screen overflow-hidden bg-[#fbfaf8] text-[#18202b]">
    <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6 lg:px-10">
      <div className="flex items-center gap-2.5"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#18202b] text-sm font-black text-white">b.</div><span className="text-sm font-extrabold tracking-[-.03em]">blogmate</span></div>
      <div className="flex items-center gap-3"><a href="#pricing" className="hidden text-xs font-bold text-[#6f777e] sm:block">요금제</a><button onClick={startKakaoLogin} className="rounded-lg bg-[#fee500] px-4 py-2.5 text-xs font-extrabold text-[#3c1e1e] shadow-sm transition hover:-translate-y-0.5">카카오로 시작하기</button></div>
    </header>
    <main>
      <section className="relative mx-auto grid max-w-6xl items-center gap-12 px-6 pb-20 pt-14 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:pb-28 lg:pt-24">
        <div className="relative z-10"><p className="mb-5 text-[11px] font-extrabold uppercase tracking-[.2em] text-[#e86550]">Naver blog workflow for local brands</p><h1 className="font-display text-[44px] leading-[1.08] tracking-[-.06em] sm:text-[62px]">우리 매장의 결을<br/><em className="text-[#e86550]">꾸준히</em> 쓰는 방법.</h1><p className="mt-7 max-w-lg text-[15px] leading-7 text-[#707980]">글쓰기가 막막한 소상공인을 위해, 브랜드 톤부터 검색 의도까지 한 번에 정리하는 네이버 블로그 초안 도구입니다.</p><div className="mt-8 flex flex-wrap items-center gap-3"><button onClick={startKakaoLogin} className="group flex items-center gap-2 rounded-xl bg-[#18202b] px-5 py-3.5 text-xs font-extrabold text-white shadow-lg shadow-[#18202b]/10 transition hover:-translate-y-0.5">무료로 워크스페이스 만들기 <ArrowRight size={15} className="transition group-hover:translate-x-1"/></button><a href="#how" className="rounded-xl px-3 py-3.5 text-xs font-bold text-[#747c83]">어떻게 쓰나요?</a></div><p className="mt-4 text-[10px] font-semibold text-[#a2a8ac]">카카오 간편가입 · 네이버 수동 발행 · 브랜드별 12건</p></div>
        <div className="relative mx-auto w-full max-w-[470px]"><div className="absolute -inset-5 rounded-[36px] bg-[#f3e9df] blur-2xl"/><div className="relative rotate-2 rounded-[24px] border border-[#e7e0d8] bg-white p-4 shadow-2xl shadow-[#b8a898]/20"><div className="rounded-[17px] bg-[#18202b] p-6 text-white"><div className="flex items-center justify-between"><span className="rounded-full bg-white/10 px-2.5 py-1 text-[9px] font-bold text-[#f5b0a2]">DRAFT READY</span><Sparkles size={16} className="text-[#f5b0a2]"/></div><p className="mt-12 font-display text-3xl leading-tight">성수동 도자기<br/><em className="text-[#f5b0a2]">처음이어도 괜찮은 하루</em></p><div className="mt-10 border-t border-white/10 pt-4"><div className="flex justify-between text-[10px] text-[#b5bdc3]"><span>SEO score</span><strong className="text-[#f5b0a2]">94 / 100</strong></div><div className="mt-2 h-1.5 rounded-full bg-white/10"><div className="h-full w-[94%] rounded-full bg-[#e86550]"/></div></div></div><div className="flex items-center justify-between px-2 pt-3 text-[10px] font-bold text-[#8d969d]"><span>오늘의공방 · Brand voice</span><span className="text-[#e86550]">편집하기 →</span></div></div><div className="absolute -bottom-5 -left-7 rounded-2xl border border-[#e9e0d9] bg-white px-4 py-3 shadow-xl shadow-[#b8a898]/15"><p className="text-[9px] font-extrabold uppercase tracking-[.15em] text-[#a0a7ab]">This month</p><p className="mt-1 text-lg font-extrabold">12 <span className="text-[10px] text-[#8c959a]">drafts ready</span></p></div></div>
      </section>
      <section id="how" className="border-y border-[#eee8e2] bg-white"><div className="mx-auto max-w-6xl px-6 py-16 lg:px-10 lg:py-20"><div className="max-w-xl"><p className="text-[11px] font-extrabold uppercase tracking-[.2em] text-[#e86550]">A calmer content system</p><h2 className="mt-3 font-display text-3xl leading-tight tracking-[-.05em] sm:text-4xl">대신 써주는 것이 아니라,<br/>계속 쓸 수 있게 만듭니다.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-3">{features.map(({ icon: Icon, title, body }, i) => <div key={title} className="rounded-2xl border border-[#eee8e2] bg-[#fbfaf8] p-6"><div className="flex items-center justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff0ec] text-[#e86550]"><Icon size={18}/></div><span className="font-mono-custom text-[10px] text-[#c0c4c6]">0{i + 1}</span></div><h3 className="mt-8 text-sm font-extrabold">{title}</h3><p className="mt-3 text-xs leading-6 text-[#7d868d]">{body}</p></div>)}</div></div></section>
      <section id="pricing" className="mx-auto max-w-6xl px-6 py-16 lg:px-10 lg:py-24"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-[11px] font-extrabold uppercase tracking-[.2em] text-[#e86550]">Simple plans</p><h2 className="mt-3 font-display text-3xl tracking-[-.05em]">브랜드 하나부터 시작하세요.</h2></div><p className="max-w-sm text-xs leading-6 text-[#7d868d]">월 12건은 브랜드 하나마다 제공됩니다. 연간 결제는 20% 할인되며, 매장을 추가하면 브랜드 슬롯을 추가할 수 있습니다.</p></div><div className="mt-6 rounded-xl bg-[#fff8f6] px-4 py-3 text-center text-xs font-bold text-[#c8513e]">연간 결제 시 2개월 무료 · 베이직 연 ₩768,000 · 프로 연 ₩1,344,000</div><div className="mt-6 grid gap-4 md:grid-cols-3">{[["베이직", "₩80,000", "₩768,000", "브랜드 1개 · 월 12건"], ["프로", "₩140,000", "₩1,344,000", "브랜드 2개 · 각각 월 12건"], ["스튜디오", "₩260,000", "₩2,496,000", "브랜드 5개 · 각각 월 12건"]].map(([name, monthly, yearly, detail], i) => <div key={name} className={`rounded-2xl border p-6 ${i === 1 ? "border-[#e86550] bg-[#fff8f6] shadow-lg shadow-[#e86550]/5" : "border-[#e7e2dc] bg-white"}`}><div className="flex items-center justify-between"><h3 className="text-sm font-extrabold">{name}</h3>{i === 1 && <span className="rounded-full bg-[#e86550] px-2 py-1 text-[9px] font-extrabold text-white">추천</span>}</div><p className="mt-6 text-3xl font-extrabold tracking-[-.05em]">{monthly}<span className="text-[10px] font-medium text-[#9aa1a5]"> /월</span></p><p className="mt-2 text-[10px] font-bold text-[#e86550]">연간 {yearly} · 20% 할인</p><p className="mt-3 text-xs font-bold text-[#e86550]">{detail}</p><div className="mt-6 space-y-2 text-[11px] text-[#727c83]"><p className="flex gap-2"><Check size={14} className="text-[#33805e]"/> 브랜드 톤 프로필</p><p className="flex gap-2"><Check size={14} className="text-[#33805e]"/> SEO 체크리스트</p><p className="flex gap-2"><Check size={14} className="text-[#33805e]"/> 모바일 미리보기</p></div><button onClick={startKakaoLogin} className={`mt-7 w-full rounded-xl py-3 text-xs font-extrabold ${i === 1 ? "bg-[#18202b] text-white" : "border border-[#e7e2dc] text-[#606a73]"}`}>카카오로 시작하기</button></div>)}</div></section>
      <section className="bg-[#18202b] px-6 py-16 text-center text-white lg:px-10 lg:py-20"><p className="font-display text-3xl tracking-[-.05em] sm:text-4xl">이번 달 첫 글부터,<br/><em className="text-[#f49c8b]">우리답게</em> 시작해보세요.</p><button onClick={startKakaoLogin} className="mt-7 rounded-xl bg-[#f49c8b] px-5 py-3.5 text-xs font-extrabold text-[#18202b]">무료로 시작하기 <ArrowRight className="ml-1 inline" size={14}/></button></section>
    </main>
    <footer className="mx-auto flex max-w-6xl flex-col gap-2 px-6 py-8 text-[10px] text-[#a2a8ac] sm:flex-row sm:justify-between lg:px-10"><span>© 2026 blogmate</span><span>브랜드의 결을 지키는 네이버 블로그 워크플로</span></footer>
  </div>;
}
