import { ArrowRight, Check, Clock3, PenLine, Search, Sparkles, WandSparkles } from "lucide-react";
import { startKakaoLogin } from "@/const";

const features = [
  { icon: PenLine, title: "클릭을 부르는 제목 후보 3개", body: "검색자의 눈길을 끄는 안전한 제목 3개를 추천해 드립니다. 마음에 드는 제목을 골라 원클릭으로 본문에 적용하세요." },
  { icon: Search, title: "네이버 검색 가이드 기반 SEO 점검", body: "의미 없는 키워드 도배는 저품질의 지름길입니다. 제목·도입부 일치성, 소제목 구조, 문단 가독성을 실시간으로 확인해 드립니다." },
  { icon: WandSparkles, title: "모바일 1초 검수 & 안전한 직접 발행", body: "저품질 제재 위험이 있는 자동 발행 프로그램이 아닙니다. 모바일 화면 그대로 검수한 뒤, 네이버 블로그에 직접 복사해서 안전하게 발행하세요." },
];

const planKey = (index: number) => index === 0 ? "Starter" : index === 1 ? "Growth" : "Studio";

export default function Landing() {
  return (
    <div className="min-h-screen overflow-hidden bg-[#fbfaf8] text-[#18202b]">
      <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6 lg:px-10">
        <div className="flex items-center gap-2.5"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#18202b] text-sm font-black text-white">b.</div><span className="text-sm font-extrabold tracking-[-.03em]">blogmate</span></div>
        <div className="flex items-center gap-3"><div className="hidden items-center gap-4 sm:flex"><a href="#how" className="text-xs font-bold text-[#6f777e]">어떻게 쓰나요?</a><a href="#pricing" className="text-xs font-bold text-[#6f777e]">요금제</a><a href="#faq" className="text-xs font-bold text-[#6f777e]">FAQ</a></div><button onClick={() => startKakaoLogin()} className="rounded-lg bg-[#fee500] px-4 py-2.5 text-xs font-extrabold text-[#3c1e1e] shadow-sm transition hover:-translate-y-0.5">카카오로 시작하기</button></div>
      </header>

      <main>
        <section className="relative mx-auto grid max-w-6xl items-center gap-12 px-6 pb-20 pt-12 lg:grid-cols-[.92fr_1.08fr] lg:px-10 lg:pb-28 lg:pt-20">
          <div className="relative z-10">
            <p className="mb-5 text-[11px] font-extrabold uppercase tracking-[.2em] text-[#e86550]">현장 일하랴, 고객 받으랴 바쁜 사장님을 위한 네이버 블로그 워크플로</p>
            <h1 className="font-display text-[43px] leading-[1.08] tracking-[-.06em] sm:text-[62px]">오늘도<br/><span className="text-[#e86550]">“블로그 써야 하는데…”</span><br/>생각만 하다 하루가 끝났나요?</h1>
            <p className="mt-7 max-w-lg text-[15px] leading-7 text-[#707980]">필라테스 수업 마치고, 미용실 마감하고, 누수·인테리어 현장 다녀와 녹초가 된 저녁. 키보드 앞에 앉으면 첫 문장부터 막막합니다. 대행사를 쓰자니 우리 매장을 전혀 모르는 영혼 없는 글에 매달 수십만 원이 나가고, 직접 쓰자니 3시간이 훌쩍 지나갑니다. blogmate는 사장님의 시간과 체력을 지키면서 우리 매장다운 진짜 초안을 만들어드립니다.</p>
            <div className="mt-8 flex flex-wrap items-center gap-3"><button onClick={() => startKakaoLogin()} className="group flex items-center gap-2 rounded-xl bg-[#18202b] px-5 py-3.5 text-xs font-extrabold text-white shadow-lg shadow-[#18202b]/10 transition hover:-translate-y-0.5">무료로 워크스페이스 만들기 <ArrowRight size={15} className="transition group-hover:translate-x-1"/></button><a href="#agitation" className="rounded-xl px-3 py-3.5 text-xs font-bold text-[#747c83]">왜 필요한가요?</a></div>
            <p className="mt-4 text-[10px] font-semibold text-[#a2a8ac]">카카오 간편가입 · 네이버 직접 검수·발행 · 브랜드별 월 12건</p><p className="mt-2 max-w-md text-[10px] leading-5 text-[#a2a8ac]">카카오로 시작하면 서비스 이용을 위해 카카오 계정 식별자와 제공되는 기본 프로필 정보를 처리할 수 있습니다. <a href="/privacy" target="_blank" rel="noreferrer" className="rounded-sm font-bold text-[#727c83] underline underline-offset-2 hover:text-[#e86550] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#e86550] focus-visible:ring-offset-2">개인정보 처리방침</a></p>
          </div>
          <div className="relative mx-auto w-full max-w-[560px]"><div className="absolute -inset-6 rounded-[40px] bg-[#f3e9df] blur-2xl"/><div className="relative overflow-hidden rounded-[28px] border border-[#e7e0d8] bg-white p-2 shadow-2xl shadow-[#b8a898]/20"><img src="/manus-storage/blogmate-hero-owner_13b778bc.png" alt="영업을 마친 뒤 블로그 초안을 고민하는 소상공인" className="h-[390px] w-full rounded-[22px] object-cover object-center sm:h-[500px]"/><div className="absolute inset-x-8 bottom-8 rounded-2xl border border-white/20 bg-[#18202b]/95 p-5 text-white backdrop-blur"><div className="flex items-center justify-between"><span className="rounded-full bg-white/10 px-2.5 py-1 text-[9px] font-bold text-[#f5b0a2]">DRAFT READY</span><Sparkles size={16} className="text-[#f5b0a2]"/></div><p className="mt-4 font-display text-2xl leading-tight">사장님은 현장과 고객에 집중하세요.<br/><em className="text-[#f5b0a2]">글감과 업체다운 구조는 blogmate가.</em></p><div className="mt-4 flex items-center justify-between text-[10px] text-[#b5bdc3]"><span>업체 지식 브리프 · 네이버 SEO · 제목 후보 3개</span><strong className="text-[#f5b0a2]">94 / 100</strong></div></div></div><div className="absolute -bottom-5 -left-5 rounded-2xl border border-[#e9e0d9] bg-white px-4 py-3 shadow-xl shadow-[#b8a898]/15"><p className="text-[9px] font-extrabold uppercase tracking-[.15em] text-[#a0a7ab]">This month</p><p className="mt-1 text-lg font-extrabold">12 <span className="text-[10px] text-[#8c959a]">drafts / brand</span></p></div></div>
        </section>

        <section id="agitation" className="border-y border-[#eee8e2] bg-[#18202b] text-white"><div className="mx-auto grid max-w-6xl items-center gap-10 px-6 py-16 lg:grid-cols-[.9fr_1.1fr] lg:px-10 lg:py-24"><div><p className="text-[11px] font-extrabold uppercase tracking-[.2em] text-[#f49c8b]">대행사를 쓰기도, 직접 쓰기도 애매했던 이유</p><h2 className="mt-4 font-display text-4xl leading-tight tracking-[-.06em] sm:text-5xl">하루 종일 땀 흘린 사장님이<br/><em className="text-[#f49c8b]">밤마다 모니터와 씨름해야 할까요?</em></h2><p className="mt-6 max-w-md text-sm leading-7 text-[#b9c0c5]">블로그 대행사에 맡겨보셨다면 아실 겁니다. 우리 매장의 장비, 시공 노하우, 진짜 가격도 모른 채 엉뚱한 키워드만 복사해 붙여넣은 글. 결국 비싼 월 비용만 나가고 손님 문의는 오지 않습니다.<br/><br/>그렇다고 직접 쓰자니 포스팅 하나에 끙끙대는 3시간. 내일 영업과 체력을 갉아먹는 블로그 스트레스, 이제 다른 방식으로 풀어야 합니다.</p><div className="mt-8 flex items-center gap-3 text-xs font-bold text-[#f5b0a2]"><Clock3 size={17}/> 3시간의 글쓰기 노동을 10분의 꼼꼼한 검수로 단축하세요.</div></div><div className="overflow-hidden rounded-[26px] border border-white/10 bg-white/5"><img src="/manus-storage/blogmate-relief-visual_f30f93b5.png" alt="블로그 글쓰기에 지친 상태와 정리된 초안을 준비한 상태의 대비" className="h-[300px] w-full object-cover sm:h-[390px]"/></div></div></section>

        <section id="how" className="bg-white"><div className="mx-auto max-w-6xl px-6 py-16 lg:px-10 lg:py-24"><div className="max-w-xl"><p className="text-[11px] font-extrabold uppercase tracking-[.2em] text-[#e86550]">매번 프롬프트 치는 AI와 다릅니다</p><h2 className="mt-3 font-display text-3xl leading-tight tracking-[-.05em] sm:text-4xl">서비스·가격·지역·전문 노하우를<br/><span className="text-[#e86550]">딱 한 번만 등록해 두세요.</span></h2><p className="mt-5 text-sm leading-7 text-[#727c83]">Blogmate AI는 허구의 소설을 쓰지 않습니다. 사장님이 등록해 둔 실제 시공 과정, 원장 직강 레슨, 투명한 가격 기준, 자주 묻는 질문(FAQ)을 바탕으로만 글을 작성합니다. 매번 AI에게 구구절절 설명하지 않아도 우리 매장다운 진짜 글이 완성됩니다.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{features.map(({ icon: Icon, title, body }, i) => <div key={title} className="rounded-2xl border border-[#eee8e2] bg-[#fbfaf8] p-6 transition hover:-translate-y-1 hover:shadow-lg hover:shadow-[#18202b]/5"><div className="flex items-center justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff0ec] text-[#e86550]"><Icon size={18}/></div><span className="font-mono-custom text-[10px] text-[#c0c4c6]">0{i + 1}</span></div><h3 className="mt-8 text-sm font-extrabold">{title}</h3><p className="mt-3 text-xs leading-6 text-[#7d868d]">{body}</p></div>)}</div></div></section>

        <section id="pricing" className="mx-auto max-w-6xl px-6 py-16 lg:px-10 lg:py-24"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-[11px] font-extrabold uppercase tracking-[.2em] text-[#e86550]">Simple plans</p><h2 className="mt-3 font-display text-3xl tracking-[-.05em]">월 8만원으로, 사장님의 저녁 시간을 되찾으세요.</h2></div><p className="max-w-sm text-xs leading-6 text-[#7d868d]">월 12건은 브랜드 하나마다 독립적으로 제공됩니다 (주 3회 발행에 최적화). 연간 결제는 20% 할인되며, 매장을 추가하면 브랜드 슬롯을 추가할 수 있습니다.</p></div><div className="mt-6 rounded-xl bg-[#fff8f6] px-4 py-3 text-center text-xs font-bold text-[#c8513e]">연간 결제 시 2개월 무료 · 베이직 연 ₩768,000 · 프로 연 ₩1,344,000</div><div className="mt-6 grid gap-4 md:grid-cols-3">{[["베이직", "₩80,000", "₩768,000", "브랜드 1개 · 월 12건 (주 3회 발행)"], ["프로", "₩140,000", "₩1,344,000", "브랜드 2개 · 각각 월 12건 (2개 매장 추천)"], ["스튜디오", "₩260,000", "₩2,496,000", "브랜드 5개 · 각각 월 12건"]].map(([name, monthly, yearly, detail], i) => <div key={name} className={`rounded-2xl border p-6 ${i === 1 ? "border-[#e86550] bg-[#fff8f6] shadow-lg shadow-[#e86550]/5" : "border-[#e7e2dc] bg-white"}`}><div className="flex items-center justify-between"><h3 className="text-sm font-extrabold">{name}</h3>{i === 1 && <span className="rounded-full bg-[#e86550] px-2 py-1 text-[9px] font-extrabold text-white">추천</span>}</div><p className="mt-6 text-3xl font-extrabold tracking-[-.05em]">{monthly}<span className="text-[10px] font-medium text-[#9aa1a5]"> /월</span></p><p className="mt-2 text-[10px] font-bold text-[#e86550]">연간 {yearly} · 20% 할인</p><p className="mt-3 text-xs font-bold text-[#e86550]">{detail}</p><div className="mt-6 space-y-2 text-[11px] text-[#727c83]"><p className="flex gap-2"><Check size={14} className="text-[#33805e]"/> 브랜드 톤 프로필</p><p className="flex gap-2"><Check size={14} className="text-[#33805e]"/> SEO 체크리스트</p><p className="flex gap-2"><Check size={14} className="text-[#33805e]"/> 모바일 미리보기</p></div><div className="mt-7 grid gap-2"><button onClick={() => startKakaoLogin(planKey(i), "monthly")} className={`w-full rounded-xl py-3 text-xs font-extrabold ${i === 1 ? "bg-[#18202b] text-white" : "border border-[#e7e2dc] text-[#606a73]"}`}>월 결제 신청하기</button><button onClick={() => startKakaoLogin(planKey(i), "yearly")} className="w-full rounded-xl border border-dashed border-[#e86550]/40 py-2.5 text-[11px] font-bold text-[#c8513e]">연간 결제 신청 · 20% 할인</button></div></div>)}</div></section>

        <section id="faq" className="border-t border-[#eee8e2] bg-white"><div className="mx-auto max-w-4xl px-6 py-16 lg:px-10 lg:py-24"><div className="text-center"><p className="text-[11px] font-extrabold uppercase tracking-[.2em] text-[#e86550]">Questions, answered</p><h2 className="mt-3 font-display text-3xl tracking-[-.05em] sm:text-4xl">시작하기 전에, 궁금한 점</h2><p className="mx-auto mt-4 max-w-xl text-xs leading-6 text-[#7d868d]">발행 한도와 결제 절차를 미리 확인하고 우리 매장에 맞는 플랜을 선택하세요.</p></div><div className="mt-10 divide-y divide-[#eee8e2] rounded-2xl border border-[#e7e2dc] bg-[#fbfaf8] px-5 sm:px-8">{[["브랜드당 월 12건은 어떤 의미인가요?", "베이직은 브랜드 1개에 월 12건을 제공합니다. 프로는 브랜드 2개에 각각 월 12건씩, 스튜디오는 브랜드 5개에 각각 월 12건씩 사용할 수 있습니다. 여러 매장을 하나의 브랜드로 묶어 12건을 나누는 방식이 아니라, 등록한 브랜드마다 독립적으로 한도가 적용되어 주 3회 정기 발행에 최적화되어 있습니다."], ["월 12건을 다 쓰지 않으면 다음 달로 이월되나요?", "월간 생성 한도는 매월 새로 계산되며, 사용하지 않은 건수는 다음 달로 이월되지 않습니다. 초안 생성에 성공한 경우에만 해당 브랜드의 사용량이 차감되고, 초안별 재생성은 별도 정책에 따라 제한됩니다."], ["월 결제를 클릭하면 바로 자동 결제되나요?", "현재 MVP에서는 자동 결제 대신 수동 청구서 방식으로 운영합니다. 플랜의 결제를 선택하면 이름, 사업자명, 연락처를 입력하는 청구서 신청 화면으로 이동하고, 신청이 접수되면 운영자가 결제선생을 통해 카카오 알림톡 모바일 청구서를 발송합니다."], ["결제선생으로 수납한 뒤에는 어떻게 이용하나요?", "카카오 알림톡으로 도착한 청구서를 확인하고 카드 또는 간편결제로 수납을 완료하시면, 운영자가 관리자 운영 센터에서 확인 후 즉시 이용 기간을 활성화해 드립니다. 고객은 대시보드에서 브랜드별 잔여 생성 횟수와 구독 상태를 실시간으로 확인할 수 있습니다."], ["결제 후 네이버 블로그에 자동으로 발행되나요?", "아닙니다. 네이버 블로그는 인위적인 자동 API 발행 시 어뷰징 제재 위험이 있습니다. Blogmate AI는 100% 안전한 운영을 위해 고품질 초안, 브랜드 톤 반영, SEO 점검, 모바일 미리보기를 제공하며, 최종 발행은 사장님이 직접 검수한 뒤 복사하여 수동으로 진행합니다."]].map(([question, answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-extrabold text-[#18202b] [&::-webkit-details-marker]:hidden"><span>{question}</span><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full border border-[#ded7d0] text-lg font-normal text-[#e86550] transition group-open:rotate-45">+</span></summary><p className="max-w-3xl pr-10 pt-4 text-xs leading-6 text-[#727c83]">{answer}</p></details>)}</div></div></section>

        <section className="bg-[#18202b] px-6 py-16 text-center text-white lg:px-10 lg:py-20"><p className="font-display text-3xl tracking-[-.05em] sm:text-4xl">오늘 저녁부터,<br/><em className="text-[#f49c8b]">블로그 숙제에서 해방되세요.</em></p><p className="mx-auto mt-4 max-w-md text-xs leading-6 text-[#b9c0c5]">더 이상 퇴근 후 빈 화면을 보며 한숨 쉬지 마세요. 카카오 간편가입으로 1분 만에 우리 업체를 등록하고 첫 초안을 확인해보세요.</p><button onClick={() => startKakaoLogin()} className="mt-7 rounded-xl bg-[#f49c8b] px-5 py-3.5 text-xs font-extrabold text-[#18202b]">무료로 시작하기 <ArrowRight className="ml-1 inline" size={14}/></button></section>
      </main>
      <footer className="mx-auto flex max-w-6xl flex-col gap-3 px-6 py-8 text-[10px] text-[#a2a8ac] sm:flex-row sm:items-center sm:justify-between lg:px-10"><span>© 2026 blogmate</span><div className="flex flex-wrap items-center gap-4"><a href="/privacy" className="font-bold text-[#727c83] hover:text-[#e86550]">개인정보 처리방침</a><span>브랜드의 결을 지키는 네이버 블로그 워크플로</span></div></footer>
    </div>
  );
}
